### ISSUE TITLE
What's the point of unpacking an open-source application?

### ISSUE THREAD

**Issue by momo5502** [illnyang/iw4x-mod-builder#1]

**Comment by illnyang** [comment]
Hi Maurice!! Did not expect to see you here. l've learned only recently that this code is of your creation, and that it's rather old.

I took a quick glance over your repos, but didn't find the source code there. Mind sending a link?

On a sidenote, see my reply @ UC to you, in the same topic. I left a genuine protip there, which I would have sent you @ Discord if JTAG didn't ban me preemptively. 

I'm not really serious about being an adversary to Plutonium, though. Helping cheating kids is the last thing on my mind, so don't worry about that. I've dumped all of Plutonium's component info + offsets, for each supported game. I'm in the process of coalescing open-iw5, iw4x, iw3xo & plutonium patchsets into a single monolith project.

Another protip, in reward for reaching out to me instead of playing "gray rock": Themida doesn't strip RTTII, all of Pluto's components are named verbatim in the binary...

**Comment by momo5502** [comment]
You literally linked the source code:
![image](https://user-images.githubusercontent.com/4027748/160287983-e7b2962e-80bd-4099-b344-2fc9c72dd6ff.png)

**Comment by momo5502** [comment]
You probably overlooked, that it is on a different branch: https://github.com/XLabsProject/iw4x-mod-builder/tree/main

**Comment by illnyang** [comment]
Github played me dirty, it doesn't show stale branches unless you dig deeper. Besides, I assumed that the source code is not available, because Enigma. Consider this repo to be an even bigger source of laughs, then :P

**Comment by illnyang** [comment]
I will update the README.md accordingly later.

**Comment by illnyang** [comment]
This leaves me wondering even more, though. JTAG banned me for unpacking the modtool, which is open source anyway. His & Rekti's defensiveness seems even more irrational to me now......
